### ISSUE TITLE
Alexa Simulator: Ensure compatibility with the new Testing Beta interface

### ISSUE THREAD

**Issue by krunchness** [alleyinteractive/voicewp#117]
Hello Tom,

i have a problem on the utterance or invocation of the skill under development in Alexa Simulator 
When asking alexa and using the invocation it says "There was a problem with the requested skill's response" . 

See attached : 

![invocation](https://user-images.githubusercontent.com/24386070/37658784-4af2fc12-2c89-11e8-848f-5211b1048c9c.PNG)
![settings](https://user-images.githubusercontent.com/24386070/37658788-4c709aa4-2c89-11e8-8468-7942204d7541.PNG)
![test simulator](https://user-images.githubusercontent.com/24386070/37658791-4e90ec44-2c89-11e8-879e-f40b74961b2c.PNG)

Thanks!

**Comment by tomharrigan** [comment]
Note for others viewing this: We discussed the issue in other channels, looks like it's specific to the new Testing Beta interface. Will be looking into for during the next release of the plugin, but everything still works without issue using the regular testing interface (rather than the Beta)

**Comment by krunchness** [comment]
Regarding this i found that the Alexa Simulator beta's return of "applicationID" was not matched on the current skill when invocation was triggered. 

![test-simulator](https://user-images.githubusercontent.com/24386070/37661068-e19f986e-2c8e-11e8-8472-114f14a01911.PNG)
![test-simulator-2](https://user-images.githubusercontent.com/24386070/37661071-e2c6de8c-2c8e-11e8-907a-a770b30acac8.PNG)


And on the regular testing interface ( old testing ) where it was working fine . it returns the correct applicationID

![old-test-simulator](https://user-images.githubusercontent.com/24386070/37661266-63c52c5a-2c8f-11e8-98a3-9ea158263381.PNG)

**Comment by tomharrigan** [comment]
Interesting, thanks for digging in further on this :)

**Comment by tomharrigan** [comment]
Note for future viewers: Issue in this case was that user created two skills for the same endpoint, thus they both had different ID's, and the skill being tested was not the one which had the amazon app ID associated to the WordPress app.

**Comment by krunchness** [comment]
Additional : 

The two skills had the same invocation name .

Thanks tom! :)
