### ISSUE TITLE
Consider adding a PHP version requirement in the readme

### ISSUE THREAD

**Issue by jgraup** [alleyinteractive/voicewp#15]
I noticed the use of `[]` for an `array()`. Considering that syntax will break in lower versions of PHP, it's worth mentioning as part of the requirements. Also, since you're using the REST API would make sense to add an initial WP/plugin version as well to the requirements. These are both very minor yet useful for those new to the project.

**Comment by tomharrigan** [comment]
Very good point. Thanks! Totally forgot about that.
