### ISSUE TITLE
Add GA support

### ISSUE THREAD

**Issue by tomharrigan** [alleyinteractive/voicewp#40]
Implement GA's server-side Measurement Protocol to handle sending custom events to GA based on firing certain intents

**Comment by dlh01** [comment]
This might have been a route you were already considering, but if the plugin started this effort by implementing a set of `do_action()` calls to signal events, it would (a) allow sites with existing server-side analytics integrations to use their own rigs, and (b) allow the plugin to dogfood those actions by way of its own GA integration.

**Comment by tomharrigan** [comment]
With the addition of the metrics dashboard, this is now a very low priority in my eyes.
https://developer.amazon.com/blogs/alexa/post/2b3912a9-c6ec-4642-9c1a-55c42d0f14b6/leverage-the-new-metrics-dashboard-to-deepen-skill-engagement-drive-retention1

**Comment by tomharrigan** [comment]
Re-open if needed
