### ISSUE TITLE
Allow specifying phrases that should be "read out"

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/voicewp#45]
A news organization might be used to writing abbreviations for the web that don't make sense when spoken. 

For example, "DOT" in a news story should probably be spoken as "Department of Transportation," not "dot."

It would be nice to provide an interface that allows sites to list words or phrases that shouldn't be read as-is and to specify how those should be replaced.

The plugin might also be able to provide some starter replacements, like "in the morning" for "a.m.", although these should be removable if provided.

**Comment by tomharrigan** [comment]
Thoughts on implementation:
1) Add a field in the main Alexa Skill Settings screen to define a list of words that get pronounced differently, maybe a format such as:
`a.m. | in the morning,
DOT | Department of Transportation`
open to better methods than a pipe character separator 
2.) on `save_post`, filter the content and insert the `<sub alias="">` SSML for any matches, so: `<sub alias="Department of Transportation">DOT</sub>`

That way it only runs once, and in conjunction with #32 allows for reading out specific phrases in a user defined way
