### ISSUE TITLE
Does this support Speech Synthesis Markup Language (SSML) in Wordpress Posts to be read by Alexa?

### ISSUE THREAD

**Issue by msaltzm1** [alleyinteractive/voicewp#65]
Example:
**Post Title**
Read All About It

**Post Content**
<amazon:effect name="whispered"> Here it is. </amazon:effect>

[https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference#using-ssml-in-your-response](url)

**Comment by tomharrigan** [comment]
@msaltzm1 at the moment, it strips all markup from the post_content field to avoid things such as anchor tags being read out for example. Support for SSML in the content is definitely on the roadmap, but not something we've built yet. The following issue was created and assigned to a milestone to address this: #32

**Comment by tomharrigan** [comment]
Closing since #32 already exists for the same purpose

**Comment by tomharrigan** [comment]
This has now been added to the plugin. Any of the [valid SSML tags](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference) can now be used within your post content.

**Comment by msaltzm1** [comment]
@tomharrigan Thanks for the update. I updated my plugin and was sure to verify my endpoint was correct in the Amazon Developer Console. I am now receiving the following error when testing:

There was an error calling the remote endpoint, which returned HTTP 404 : Not Found

Any thoughts?

**Comment by msaltzm1** [comment]
Got it. Ignore the previous issue.  Looks great awesome!!!!

**Comment by tomharrigan** [comment]
Fantastic! I'm about to roll out some documentation updates that will include a link to our Gitter (a chat room for the project), happy to provide more real-time support, answer questions and such there if you'd like https://gitter.im/voicewp/Lobby
