### ISSUE TITLE
Project outdated?

### ISSUE THREAD

**Issue by OliverWagner** [alleyinteractive/voicewp#98]
I tried to setup voicewp according to the documentation, but the Alexa Dev Console responds with different errors.

There seems to be an issue with the interaction module and when entering my https URL it resonds with Error: The information sent is out of date, please refresh and try again."

Can you guys help?

**Comment by OliverWagner** [comment]
Ok, managed to get this up an running.

Now, during testing, I get this service response: "The remote endpoint could not be called, or the response it returned was invalid."

But the provided URL to my JSON feed is correct. Any ideas?

**Comment by tocan** [comment]
Oliver if you get it to run.. Can you send me a german instruction? Special
i need ideas for multiside and multilanguage blogs. I never get an answer
and so without a support this plugin is useless

Daniela Tocan

Westenfelderstr. 14b
44866 Bochum
Deutschland

https://tocan.de
http://d <http://tocan.de/shop/>onau-grundel-schiff.de

2017-10-28 18:03 GMT+02:00 OliverWagner <notifications@github.com>:

**Comment by tomharrigan** [comment]
@OliverWagner DM me in the Gitter channel, happy to help you debug.

**Comment by tocan** [comment]
Gitter is new to me i did start there a communication with hello...

Maybe its because my english that i could not get it start.

**Comment by OliverWagner** [comment]
The trick is to set the SSL connection endpoint to " My development endpoint is a sub-domain of a domain that has a wildcard certificate from a certificate authority"

**Comment by tomharrigan** [comment]
Cool, closing this issue. @tocan I'm hoping to have german support/translations added to the plugin within the next month.
